require('dotenv').config();

GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
MAIL_SERVICE = process.env.MAIL_SERVICE;
MAIL_USER = process.env.MAIL_USER;
MAIL_PASSWORD = process.env.MAIL_PASSWORD;
KEY_PATH_PRIVKEY = process.env.KEY_PATH_PRIVKEY;
KEY_PATH_FULLCHAIN = process.env.KEY_PATH_FULLCHAIN;
DB_URL = process.env.DB_URL;
FRONTEND_URL = process.env.FRONTEND_URL;
PORT = process.env.PORT;
CORRECT_USER = process.env.CORRECT_USER;
REFRESH_MESSAGES_INTERVAL = process.env.REFRESH_MESSAGES_INTERVAL;
APP_PASSWORD = process.env.APP_PASSWORD;